title: Pocket Library
description: Download articles, summaries, analyses, and notes from various English Literature websites as PDF.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme